stages:
    - announce

announce:
    stage: announce
    script:
        - curl --data chat_id=$TELEGRAM_CHAT_ID --data-urlencode text="[$CI_COMMIT_REF_NAME] $CI_COMMIT_TITLE by $GITLAB_USER_NAME" $TELEGRAM_BOT_URL/sendMessage
        