stages:
    - test
    - deploy
    - announce

test:
    image: node:12.13-alpine
    stage: test
    variables:
        ENVIRONMENT: TESTING
        DB_TESTING: "mongodb://localhost:27018/test"
    services:
        - mongo:latest
    script:
        - echo $DB_TESTING
        - npm install
        - npm test
    only:
        - development
        
deploy:
    image: ruby:2.5.6
    stage: deploy
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    only:
        - development



announce:
    stage: announce
    script:
        - curl --data chat_id=$TELEGRAM_CHAT_ID --data-urlencode text="[$CI_COMMIT_REF_NAME] $CI_COMMIT_TITLE by $GITLAB_USER_NAME" $TELEGRAM_BOT_URL/sendMessage
    only:
        - development
        - master
        
